<a href="https://colab.research.google.com/github/rkp74/Numpy/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Basic



In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [3]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [4]:
# single line %timeit
# whole code %%timeit

In [5]:
%timeit [j**4 for j in range(1,9)]

2.76 µs ± 471 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
%timeit  np.array([j**4 for j in range(1,9)])

3.73 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%timeit np.arange(1,9)**4

2.3 µs ± 60.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
#1l = []
#for i in range(1,5):
  #int_1 = int(input("Enter :"))
  #l.append(int_1)

#print(np.array(l))

In [9]:
ar2 = np.array([[1,2,3,4] , [5,6,7]])
print(ar2)
print(ar2.ndim)
ar2


[list([1, 2, 3, 4]) list([5, 6, 7])]
1


<ipython-input-9-2686dc72cf7c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = np.array([[1,2,3,4] , [5,6,7]])


array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [10]:
ar3 = np.array([[[1,2,3,4,5]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4 5]]]
3


In [11]:
arn = np.array([1,2,3,4] , ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Zero array

In [12]:
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [13]:
ar_zero1 = np.zeros((3,4))
print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


one array

In [14]:
ar_one = np.ones(5)
print(ar_one)

[1. 1. 1. 1. 1.]


In [15]:
ar_one2 = np.ones((3,3))
print(ar_one2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


empty array

In [16]:
ar_empty = np.empty(4)
print(ar_empty)

[0. 0. 0. 0.]


In [17]:
ar_empty2 = np.empty((3,2))
print(ar_empty2)

[[4.68116127e-310 0.00000000e+000]
 [6.83000218e-310 6.83000218e-310]
 [6.83000490e-310 6.83001162e-310]]


range array

In [18]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [19]:
ar_rn2 = np.arange(4,8)
print(ar_rn2)

[4 5 6 7]


diognal elements filled


In [20]:
ar_dig = np.eye(3)
print(ar_dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
ar_dig2 = np.eye(3,5)
print(ar_dig2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


linearly spaced array

In [22]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


rand()

In [23]:
var = np.random.rand(4)
print(var)

[0.46265564 0.85457209 0.81794331 0.15419202]


In [24]:
var1 = np.random.rand(2,5)
print(var1)

[[0.90854242 0.0030352  0.50489833 0.67849507 0.67953252]
 [0.58837876 0.38186784 0.87659048 0.32222533 0.52775217]]


randn()

In [25]:
var2 = np.random.randn(4)
print(var2)

[ 0.09836404 -0.01048149  0.10990497  0.2520909 ]


In [26]:
var3 = np.random.randn(2,5)
print(var3)

[[-0.6707093   0.73001817  1.99553434  0.11954896 -0.44104635]
 [-0.35480145  0.73532746  0.17363245 -2.08726406  0.1917528 ]]


randf()

In [27]:
var4 = np.random.ranf(4)
print(var4)

[0.06074736 0.77126235 0.09659858 0.41468225]


In [28]:
var5 = np.random.ranf(size = (3,5))
print(var5)

[[0.48842383 0.61429574 0.93016725 0.46959254 0.56475156]
 [0.57689104 0.49421145 0.51629676 0.2406738  0.49296278]
 [0.13087188 0.31370433 0.62697565 0.68067315 0.41139183]]


randint()

In [29]:
 # var6 = np.random.randint(min,max,total)
 var6 = np.random.randint(5,9,20)
 print(var6)

[8 6 7 5 8 7 8 6 8 8 5 8 6 6 6 5 6 6 7 5]


In [30]:
 var7 = np.random.randint(5,9,size=(3,5))
 print(var7)

[[6 6 6 5 7]
 [6 7 7 7 7]
 [5 8 6 5 7]]


# Data Type

In [31]:
import numpy as np

In [32]:
var = np.array([1,2,3,4,12,14,15])

print("Data type : " , var.dtype)

Data type :  int64


In [33]:
var2 = np.array([1.0,2.0,3.0])
print("Data type : " , var2.dtype)

Data type :  float64


In [34]:
var3 = np.array(["Rajan" , "Diya" , "Kajal"])
print("Data type : " , var3.dtype)

Data type :  <U5


In [35]:
var4 = np.array([True , False])
print("Data Type : ", var4.dtype)

Data Type :  bool


In [36]:
var4= np.array(["Rajan" , "Diya" , "Kajal" ,  1 , 2 ,3 ])
print("Data type : " , var4.dtype)

Data type :  <U21


In [37]:
var5 = np.array(["Rajan" , "Diya" , "Kajal" ,  1 , 2 ,3 , 2.6 , 3.8])
print("Data type : " , var5.dtype)

Data type :  <U32


In [38]:
var6 = np.array(["Rajan" , "Diya" , "Kajal" ,  1 , 2 ,3 , 2.6 , 3.8 , True])
print("Data type : " , var6.dtype)

Data type :  <U32


In [39]:
x = np.array([1,2,3,4])
print(x.dtype)

int64


In [129]:
y = np.array([1,2,3,4,4883] , dtype = np.int8)
print(y.dtype)
print(y)

int8
[ 1  2  3  4 19]


In [41]:
z = np.array([1,2,3,4] , dtype = "f")
print(z.dtype)
print(z)

float32
[1. 2. 3. 4.]


In [42]:
z1 = np.array([1,2,3,4])
new = np.float32(z1)
print(z1.dtype)
print(new.dtype)
print(z1)
print(new)

int64
float32
[1 2 3 4]
[1. 2. 3. 4.]


In [43]:
z1 = np.array([1,2,3,4])
new = np.float32(z1)
new1 = np.int_(new)
print(z1.dtype)
print(new.dtype)
print(new1.dtype)
print(z1)
print(new)
print(new1)

int64
float32
int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [44]:
t = np.array([1,2,3,4])
t1 = t.astype(float)
print(t)
print(t1)

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic Operation

In [45]:
import numpy as np

In [46]:
x = np.array([1,2,3,4])
xadd = x +3
print(xadd)

[4 5 6 7]


In [47]:
a = np.array([1,2,3,4])
b = np.array([1,5,3,8])

c = a + b
print(c)

[ 2  7  6 12]


In [48]:
d = np.array([1,2,3,4])
e = np.array([1,5,8])

# f = d + e
# print(c)


#ValueError: operands could not be broadcast together with shapes (4,) (3,)

In [49]:
a = np.array([1,2,3,4])
b = np.array([1,5,3,8])

c = np.add(a,4)
print(c)

[5 6 7 8]


In [50]:
a = np.array([1,2,3,4])
b = np.array([1,5,3,8])

c = np.add(a,b)
print(c)

[ 2  7  6 12]


In [51]:
x = np.array([1,2,3,4])
xsub = x -3
print(xsub)

[-2 -1  0  1]


In [52]:
x = np.array([1,2,3,4])
xmul = x*3
print(xmul)

[ 3  6  9 12]


In [53]:
x = np.array([1,2,3,4])
xdiv = x / 3
print(xdiv)

[0.33333333 0.66666667 1.         1.33333333]


In [54]:
x = np.array([1,2,3,4])
xmod = x % 3
print(xmod)

[1 2 0 1]


In [55]:
x = np.array([1,2,3,4])
xpow = x ** 3
print(xpow)

[ 1  8 27 64]


In [56]:
x = np.array([0,1,2,3,4])
xrec = 1/x
print(xrec)

[       inf 1.         0.5        0.33333333 0.25      ]


<ipython-input-56-878c04595f03>:2: RuntimeWarning: divide by zero encountered in divide
  xrec = 1/x


2D Array

In [57]:
var21 = np.array([[1,2,3,4]  ,  [5,6,7,8]])
var22 = np.array([[1,3,5,7] , [2,4,6,8]])

var2122 = var21 % var22
print(var2122)

[[0 2 3 4]
 [1 2 1 0]]


In [58]:
var8 = np.array([1,1,8,4,5,6,7,8])
print(np.min(var8))
print(np.max(var8))
print(np.argmin(var8)) # Position of minimum
print(np.argmax(var8)) # Position of maximum
print(np.sqrt(var8))
print(np.sin(var8))
print(np.cos(var8))
print(np.cumsum(var8))

1
8
0
2
[1.         1.         2.82842712 2.         2.23606798 2.44948974
 2.64575131 2.82842712]
[ 0.84147098  0.84147098  0.98935825 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]
[ 0.54030231  0.54030231 -0.14550003 -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003]
[ 1  2 10 14 19 25 32 40]


In [59]:
var8 = np.array([[1,1,8,4] , [4,6,7,8]])
print(np.min(var8 , axis = 0))
print(np.min(var8 , axis = 1))
print(np.max(var8, axis = 0))
print(np.argmin(var8 , axis = 1)) # Position of minimum
print(np.argmax(var8,axis = 1)) # Position of maximum
print(np.sqrt(var8))
print(np.sin(var8))
print(np.cos(var8))
print(np.cumsum(var8))
print(np.cumsum(var8, axis = 0))
print(np.cumsum(var8, axis = 1))


[1 1 7 4]
[1 4]
[4 6 8 8]
[0 0]
[2 3]
[[1.         1.         2.82842712 2.        ]
 [2.         2.44948974 2.64575131 2.82842712]]
[[ 0.84147098  0.84147098  0.98935825 -0.7568025 ]
 [-0.7568025  -0.2794155   0.6569866   0.98935825]]
[[ 0.54030231  0.54030231 -0.14550003 -0.65364362]
 [-0.65364362  0.96017029  0.75390225 -0.14550003]]
[ 1  2 10 14 18 24 31 39]
[[ 1  1  8  4]
 [ 5  7 15 12]]
[[ 1  2 10 14]
 [ 4 10 17 25]]


# shape and Reshape

Shape

In [60]:
import numpy as np

In [61]:
var10 = np.array([1,2,3,4])
print(var10.shape)

(4,)


In [62]:
var11 = np.array([[1,2,3,4], [5,6,7]])
print(var11.shape)

(2,)


<ipython-input-62-24d6b97e10b3>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  var11 = np.array([[1,2,3,4], [5,6,7]])


In [63]:
var12 = np.array([[1,2,3,4], [5,6,7,8]])
print(var12.shape)

(2, 4)


In [64]:
var13 = np.array([[[1,2],[3,4], [5,6]]])
print(var13.shape)

(1, 3, 2)


In [65]:
var14 = np.array([1,2,3,4] , ndmin = 4)

print(var14)
print(var14.ndim)
print(var14.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


Reshape

In [66]:
var15 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var15.shape)
var16 = var15.reshape(2,3,2)
print(var16)
print(var16.shape)
var16



(12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [67]:
# 3D to 1D array
var17 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
var18 = var17.reshape(-1)

print(var18)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
# 3D to 1D array
var19 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
var20 = var19.reshape(-1, var19.shape[-1])

print(var20)
print(var20.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
2


# BroadCasting Arrays

In [69]:
import numpy as np

In [70]:
var21 = np.array([1,2,3,4])
var22 = np.array([2,4,6])

# print(var21 + var22)
# ValueError: operands could not be broadcast together with shapes (4,) (3,)

In [71]:
var23 = np.array([[1,2,3]])
print(var23.shape)
print(var23)

(1, 3)
[[1 2 3]]


In [72]:
var24 = np.array([[1] , [2] , [3] ])
print(var24.shape)
print(var24)

(3, 1)
[[1]
 [2]
 [3]]


In [73]:
print(var23 + var24)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [74]:
var25 = np.array([[1] , [2]])
print(var25.shape)
var26 = np.array([[3,4,5] , [6,7,8]])

print(var25 + var26)


(2, 1)
[[ 4  5  6]
 [ 8  9 10]]


In [75]:
 var27 = np.array([[1] , [2] , [3] ])
 var28 = np.array([1,2,3,4,5])
 print(var27 + var28)

[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


# Indexing

In [76]:
import numpy as np

In [77]:
var29 = np.array([9,8,7,6])
#                 1 2 3 4
print(var29[1])

8


In [78]:
var30 = np.array([9,8,7,6])
#                -4 -3 -2 -1

print(var30[-1])

6


In [79]:
var31 = np.array([[9,8,7,6] , [4,5,6,1]])

print(var31)
print(var31.ndim)
print(var31[1][1])

[[9 8 7 6]
 [4 5 6 1]]
2
5


In [80]:
var32 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
print(var32.ndim)
print(var32.shape)
print(var32[1][2][1])
print(var32[0,0,0])

3
(2, 3, 2)
12
1


Slicing

In [81]:
var33 = np.array([9,8,7,6,1,2,3])
print(var33[1:5])
print(var33[0:])
print(var33[1:])
print(var33[1:6:2])
print(var33[::2])

[8 7 6 1]
[9 8 7 6 1 2 3]
[8 7 6 1 2 3]
[8 6 2]
[9 7 1 3]


In [132]:
var34 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
print(var34.shape)
print(var34[1,1,0:2:2])
# 1st comma 1st bracket
# 2nd comma 2nd bracket
# Treat now as 1D Vector

(2, 3, 2)
[9]


Iterating Numpy Arrays

In [83]:
var35 = np.array([1,2,3,4,5,6,7,8])
for i in var35:
  print(i)

1
2
3
4
5
6
7
8


In [84]:
var36 = np.array([[2,3],[4,5]])
for j in var36:
  print(j)

[2 3]
[4 5]


In [85]:
var37 = np.array([[2,3],[4,5]])
for j in var37:
  for i in j:
    print(i)

2
3
4
5


In [86]:
var37 = np.array([[2, 3], [4, 5]])

for row_idx, row in enumerate(var37):
    for col_idx, value in enumerate(row):
        print(f"a{row_idx}{col_idx}:", value)


a00: 2
a01: 3
a10: 4
a11: 5


In [87]:
var38 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
for i in var38:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [88]:
var39 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
for i in np.nditer(var39):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [89]:
var40 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
for i in np.nditer(var40,flags = ['buffered'] , op_dtypes=["S"]):
  print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [90]:
var41 = np.array([[[ 1,  2],[ 3,  4],[ 5,  6]],[[ 7,  8], [ 9, 10],[11, 12]]])
for i in np.ndenumerate(var41):
  print(i)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 1, 0), 3)
((0, 1, 1), 4)
((0, 2, 0), 5)
((0, 2, 1), 6)
((1, 0, 0), 7)
((1, 0, 1), 8)
((1, 1, 0), 9)
((1, 1, 1), 10)
((1, 2, 0), 11)
((1, 2, 1), 12)


Copy vs views

In [91]:
var42 = np.array([1,2,3,4])

var43 = var42.copy()
print(var42)
print(var43)
var43[0] = 12
print(var42)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [92]:
var44 = np.array([2,5,1,6,8,3,4])

var45 = var44.view()

print(var44)
print(var45)

var45[0] = 12
print(var44)

[2 5 1 6 8 3 4]
[2 5 1 6 8 3 4]
[12  5  1  6  8  3  4]


# Join and Split arrays

Join

In [93]:
import numpy as np

In [94]:
var46 = np.array([1,2,3,4])
var47 = np.array([5,6,7,8])

var48 = np.concatenate((var46,var47))

print(var48)

[1 2 3 4 5 6 7 8]


In [138]:
var49 = np.array([[1,2] , [3,4]])
var50 = np.array([[5,6] , [7,8]])

print(var49)
print(var50)
print()

var51 = np.concatenate((var49,var50) , axis = 1 )
print(var51)
print()

var52 = np.concatenate((var49,var50) , axis = 0 )
print(var52)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [96]:
var53 = np.array([1,2,3,4])
var54 = np.array([5,6,7,8])

var55 = np.stack((var53,var54), axis = 0)

print(var55)

print()

var56 = np.stack((var53,var54), axis = 1)

print(var56)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [97]:
var57 = np.array([1,2,3,4])
var58 = np.array([5,6,7,8])

var59 = np.hstack((var57,var58))
print(var59)
print()

var60 = np.vstack((var57,var58))
print(var60)
print()

var61 = np.dstack((var57,var58))
print(var61)
print()



[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]



Split

In [98]:
 var62 = np.array([1,2,3,4,5,6])
 print(var62)

 var63 = np.array_split(var62,3)
 print(var63)
 print(type(var63))

 print(var63[0])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [99]:
var64 = np.array([[1,2] , [3,4] , [5,6]])
print(var64)

var65 = np.array_split(var64 , 3)

var66 = np.array_split(var64 , 3 , axis = 1)

print(var65)
print(var65[0])

print(var66)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[[1 2]]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


# Numpy arrays functions

In [100]:
import numpy as np

In [101]:
var67 = np.array([1,2,3,4,5,2,5,2,3,1])

var68 = np.where(var67 == 2)
print(var68)

print()

var69 = np.where((var67%2) == 0)
print(var69)


(array([1, 5, 7]),)

(array([1, 3, 5, 7]),)


Search Sorted Arrays

In [102]:
var70 = np.array([1,2,3,4,6,7,8,9,10,11,12])

var71 = np.searchsorted(var70 ,5)
print(var71)

4


In [103]:
var72 = np.array([1,2,3,4,6,7,8,9,10,11,12])

var73 = np.searchsorted(var72 ,5, side = "right")
print(var73)

4


In [104]:
var74 = np.array([1,2,3,4,6,7,8,9,10,11,12])

var75 = np.searchsorted(var74 , [5,6,7] , side = "right")
print(var75)

[4 5 6]


In [105]:
var76 = np.array([1,2,3,4,5,6,10,11,12])

var77 = np.searchsorted(var76 , [7,8,9] , side = "right")
print(var77)

[6 6 6]


Sort

In [106]:
var78 = np.random.randint(1,10,8)
print(var78)
print()
var79 = np.sort(var78)
print(var79)

[1 6 4 1 2 4 1 7]

[1 1 1 2 4 4 6 7]


In [107]:
var80 = np.array(["a" , "s" , "d" , "f" , "g" , "o" , "q" , "Q" , "A"])
print(np.sort(var80))

['A' 'Q' 'a' 'd' 'f' 'g' 'o' 'q' 's']


In [108]:
var81 = np.array([[4,2,3] , [3,7,2] , [12,5,8]])

print(np.sort(var81))

[[ 2  3  4]
 [ 2  3  7]
 [ 5  8 12]]


Filter

In [109]:
var82 = np.array([1,2,3,4,5])

f = [True,False,True,False,True]

var83 = var82[f]

print(var83)
print(type(var83))

[1 3 5]
<class 'numpy.ndarray'>


shuffle

In [110]:
var84 = np.array([1,2,3,4,5])

np.random.shuffle(var84)

print(var84)

[3 5 1 2 4]


Unique

In [139]:
var85 = np.array([1,2,3,4,2,3,1,5,1,2,3,5,1,2])

var86 = np.unique(var85 , return_index = True)

print(var86)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 7]))


Resize

In [112]:
var87 = np.array([1,2,3,4,5,6])

var88 = np.resize(var87 , (2,3))

print(var88)

[[1 2 3]
 [4 5 6]]


In [113]:
var89 = np.array([1,2,3,4,5])

var90 = np.resize(var89 , (2,3))

print(var90)

# resize doesn't through error when enough elements are not present or either excess elements are present.

[[1 2 3]
 [4 5 1]]


Flatten

In [114]:
var91 = np.array([[1 ,2 ,3] , [4 ,5, 6] ])

print(var91.flatten(order = "C"))
print(var91.flatten(order = "F"))
print(var91.flatten(order = "A"))
print(var91.flatten(order = "K"))

[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [115]:
var92 = np.array([[1 ,2 ,3] , [4 ,5, 6] ])
print(np.ravel(var92 ,  order = "C"))
print(np.ravel(var92 ,  order = "F"))
print(np.ravel(var92 ,  order = "A"))
print(np.ravel(var92 ,  order = "K"))

[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


# Insert and Delete

In [116]:
import numpy as np

In [117]:
var93 = np.array([1,2,3,4])

print(var93)

var94 = np.insert(var93,4,5)
print(var94)

var95 = np.insert(var94,(2,5),(6,7))
print(var95)

[1 2 3 4]
[1 2 3 4 5]
[1 2 6 3 4 5 7]


In [118]:
var96 = np.array([1,2,3,4,5])

var97 = np.insert(var96,(2,5),6.5) # float to int(if all array elements are int)
print(var97)

[1 2 6 3 4 5 6]


In [119]:
var98 = np.array( [ [1,2] , [3,4] ])
var99 = np.insert(var98,2,(6,7) , axis = 0) # if value = 6 last all row 6 6
print(var99)

var100 = np.insert(var98,2,(6,7) , axis = 1) # if value = 6 last all coloumn 1 2 6, 3 4 7
print(var100)

[[1 2]
 [3 4]
 [6 7]]
[[1 2 6]
 [3 4 7]]


In [120]:
var101 = np.array([1,2,3,4,5])

var102 = np.append(var101,6.5)
print(var102)

[1.  2.  3.  4.  5.  6.5]


In [121]:
var103 = np.array( [ [1,2] , [3,4] ])
var104 = np.append(var103,[[6,7]] , axis = 0)
print(var104)

[[1 2]
 [3 4]
 [6 7]]


delete

In [140]:
var105 = np.array([1,2,3,4,5])

var106 = np.delete(var105,2)
print(var106)

[1 2 4 5]


# Matrix

In [123]:
import numpy as np


In [124]:
v1 = np.matrix([[1,2,3] , [1,2,3]])
print(v1)
print(type(v1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [125]:
v2 = np.array([[1,2,3] , [1,2,3]])
print(v2)
print(type(v2))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [126]:
v3 = np.matrix([[1,2],[3,4]])
v4 = np.matrix([[1,1],[2,2]])
print(v3 + v4)
print()
print(v3 - v4)
print()
print(v3 * v4)
print()
print(v3.dot(v4))

[[2 3]
 [5 6]]

[[0 1]
 [1 2]]

[[ 5  5]
 [11 11]]

[[ 5  5]
 [11 11]]


In [127]:
v3 = np.matrix([[1,2,3],[3,4,5]])
v4 = np.matrix([[1,1,2],[2,2,1]])
print(v3 + v4)
print()
print(v3 - v4)
print()
#print(v3 * v4) # shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

print()

[[2 3 5]
 [5 6 6]]

[[0 1 1]
 [1 2 4]]




In [145]:
v13 = np.matrix([[1,2,3],[3,4,5]])
print(v13.shape)
v14 = np.matrix([[1,1],[2,2] ,[2,1]])

print(v13*v14)
print(v13.dot(v14))

(2, 3)
[[11  8]
 [21 16]]
[[11  8]
 [21 16]]


In [128]:
v5 = np.matrix([[1,2,3] , [2,6,4] , [4,5,7]])
print(v5)
print()
print(np.transpose(v5))
print()
print(v5.T)
print()
print(np.swapaxes(v5,0,1))
print()
print(np.linalg.inv(v5))
print()
print(np.linalg.matrix_power(v5,2))
print()
print(np.linalg.matrix_power(v5,1))
print()
print(np.linalg.matrix_power(v5,0))
print()
print(np.linalg.matrix_power(v5,-1))
print()
print(np.linalg.matrix_power(v5,-2))
print()
print(np.linalg.det(v5))

[[1 2 3]
 [2 6 4]
 [4 5 7]]

[[1 2 4]
 [2 6 5]
 [3 4 7]]

[[1 2 4]
 [2 6 5]
 [3 4 7]]

[[1 2 4]
 [2 6 5]
 [3 4 7]]

[[-1.375  -0.0625  0.625 ]
 [-0.125   0.3125 -0.125 ]
 [ 0.875  -0.1875 -0.125 ]]

[[17 29 32]
 [30 60 58]
 [42 73 81]]

[[1 2 3]
 [2 6 4]
 [4 5 7]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[-1.375  -0.0625  0.625 ]
 [-0.125   0.3125 -0.125 ]
 [ 0.875  -0.1875 -0.125 ]]

[[ 2.4453125  -0.05078125 -0.9296875 ]
 [ 0.0234375   0.12890625 -0.1015625 ]
 [-1.2890625  -0.08984375  0.5859375 ]]

-16.000000000000007
